name: Unit Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.yaml'
  workflow_dispatch: # To manually run the workflow

jobs:

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Delete previous Builds
      run: flutter clean

    - name: Get Flutter Pub
      run: flutter pub get
    
    - name: Set up Dart Pub
      run: dart pub get
    
    - name: Analyze Flutter Code
      run: flutter analyze
    
    - name: Flutter Test
      run: flutter test
